apiVersion: application.zitadel.didactiklabs.io/v1alpha1
kind: Oidc
metadata:
  name: grafana
spec:
  forProvider:
    accessTokenRoleAssertion: false
    accessTokenType: OIDC_TOKEN_TYPE_BEARER
    additionalOrigins: []
    appType: OIDC_APP_TYPE_WEB
    authMethodType: OIDC_AUTH_METHOD_TYPE_BASIC
    clockSkew: 0s
    devMode: false
    grantTypes:
      - OIDC_GRANT_TYPE_AUTHORIZATION_CODE
    idTokenRoleAssertion: false
    idTokenUserinfoAssertion: false
    name: grafana
    orgIdRef:
      name: bealv
    postLogoutRedirectUris:
      - '*'
    projectIdRef:
      name: administration
    redirectUris:
      - https://grafana.bealv.lan/login/generic_oauth
    responseTypes:
      - OIDC_RESPONSE_TYPE_CODE
    skipNativeAppSuccessPage: false
    version: OIDC_VERSION_1_0
  writeConnectionSecretToRef:
    name: grafana-oidc
    namespace: monitoring
---
apiVersion: application.zitadel.didactiklabs.io/v1alpha1
kind: Oidc
metadata:
  name: velero
spec:
  forProvider:
    accessTokenRoleAssertion: false
    accessTokenType: OIDC_TOKEN_TYPE_BEARER
    additionalOrigins: []
    appType: OIDC_APP_TYPE_WEB
    authMethodType: OIDC_AUTH_METHOD_TYPE_BASIC
    clockSkew: 0s
    devMode: false
    grantTypes:
      - OIDC_GRANT_TYPE_AUTHORIZATION_CODE
    idTokenRoleAssertion: false
    idTokenUserinfoAssertion: false
    name: velero
    orgIdRef:
      name: bealv
    postLogoutRedirectUris:
      - '*'
    projectIdRef:
      name: administration
    redirectUris:
      - https://velero.bealv.lan/login
    responseTypes:
      - OIDC_RESPONSE_TYPE_CODE
    skipNativeAppSuccessPage: false
    version: OIDC_VERSION_1_0
  writeConnectionSecretToRef:
    name: velero-ui-oidc
    namespace: velero-ui
---
apiVersion: application.zitadel.didactiklabs.io/v1alpha1
kind: Oidc
metadata:
  name: sonarr
spec:
  forProvider:
    accessTokenRoleAssertion: false
    accessTokenType: OIDC_TOKEN_TYPE_BEARER
    additionalOrigins: []
    appType: OIDC_APP_TYPE_WEB
    authMethodType: OIDC_AUTH_METHOD_TYPE_BASIC
    clockSkew: 0s
    devMode: false
    grantTypes:
      - OIDC_GRANT_TYPE_AUTHORIZATION_CODE
    idTokenRoleAssertion: false
    idTokenUserinfoAssertion: false
    name: sonarr
    orgIdRef:
      name: bealv
    postLogoutRedirectUris:
      - '*'
    projectIdRef:
      name: administration
    redirectUris:
      - https://sonarr.bealv.lan/oauth2/callback
    responseTypes:
      - OIDC_RESPONSE_TYPE_CODE
    skipNativeAppSuccessPage: false
    version: OIDC_VERSION_1_0
  writeConnectionSecretToRef:
    name: sonarr-oidc
    namespace: sonarr
---
apiVersion: application.zitadel.didactiklabs.io/v1alpha1
kind: Oidc
metadata:
  name: prowlarr
spec:
  forProvider:
    accessTokenRoleAssertion: false
    accessTokenType: OIDC_TOKEN_TYPE_BEARER
    additionalOrigins: []
    appType: OIDC_APP_TYPE_WEB
    authMethodType: OIDC_AUTH_METHOD_TYPE_BASIC
    clockSkew: 0s
    devMode: false
    grantTypes:
      - OIDC_GRANT_TYPE_AUTHORIZATION_CODE
    idTokenRoleAssertion: false
    idTokenUserinfoAssertion: false
    name: prowlarr
    orgIdRef:
      name: bealv
    postLogoutRedirectUris:
      - '*'
    projectIdRef:
      name: administration
    redirectUris:
      - https://prowlarr.bealv.lan/oauth2/callback
    responseTypes:
      - OIDC_RESPONSE_TYPE_CODE
    skipNativeAppSuccessPage: false
    version: OIDC_VERSION_1_0
  writeConnectionSecretToRef:
    name: prowlarr-oidc
    namespace: prowlarr
---
apiVersion: application.zitadel.didactiklabs.io/v1alpha1
kind: Oidc
metadata:
  name: qbittorrent
spec:
  forProvider:
    accessTokenRoleAssertion: false
    accessTokenType: OIDC_TOKEN_TYPE_BEARER
    additionalOrigins: []
    appType: OIDC_APP_TYPE_WEB
    authMethodType: OIDC_AUTH_METHOD_TYPE_BASIC
    clockSkew: 0s
    devMode: false
    grantTypes:
      - OIDC_GRANT_TYPE_AUTHORIZATION_CODE
    idTokenRoleAssertion: false
    idTokenUserinfoAssertion: false
    name: qbittorrent
    orgIdRef:
      name: bealv
    postLogoutRedirectUris:
      - '*'
    projectIdRef:
      name: administration
    redirectUris:
      - https://qbittorrent.bealv.lan/oauth2/callback
    responseTypes:
      - OIDC_RESPONSE_TYPE_CODE
    skipNativeAppSuccessPage: false
    version: OIDC_VERSION_1_0
  writeConnectionSecretToRef:
    name: qbittorrent-oidc
    namespace: qbittorrent
---
apiVersion: application.zitadel.didactiklabs.io/v1alpha1
kind: Oidc
metadata:
  name: radarr
spec:
  forProvider:
    accessTokenRoleAssertion: false
    accessTokenType: OIDC_TOKEN_TYPE_BEARER
    additionalOrigins: []
    appType: OIDC_APP_TYPE_WEB
    authMethodType: OIDC_AUTH_METHOD_TYPE_BASIC
    clockSkew: 0s
    devMode: false
    grantTypes:
      - OIDC_GRANT_TYPE_AUTHORIZATION_CODE
    idTokenRoleAssertion: false
    idTokenUserinfoAssertion: false
    name: radarr
    orgIdRef:
      name: bealv
    postLogoutRedirectUris:
      - '*'
    projectIdRef:
      name: administration
    redirectUris:
      - https://radarr.bealv.lan/oauth2/callback
    responseTypes:
      - OIDC_RESPONSE_TYPE_CODE
    skipNativeAppSuccessPage: false
    version: OIDC_VERSION_1_0
  writeConnectionSecretToRef:
    name: radarr-oidc
    namespace: radarr
---
apiVersion: application.zitadel.didactiklabs.io/v1alpha1
kind: Oidc
metadata:
  name: bazarr
spec:
  forProvider:
    accessTokenRoleAssertion: false
    accessTokenType: OIDC_TOKEN_TYPE_BEARER
    additionalOrigins: []
    appType: OIDC_APP_TYPE_WEB
    authMethodType: OIDC_AUTH_METHOD_TYPE_BASIC
    clockSkew: 0s
    devMode: false
    grantTypes:
      - OIDC_GRANT_TYPE_AUTHORIZATION_CODE
    idTokenRoleAssertion: false
    idTokenUserinfoAssertion: false
    name: bazarr
    orgIdRef:
      name: bealv
    postLogoutRedirectUris:
      - '*'
    projectIdRef:
      name: administration
    redirectUris:
      - https://bazarr.bealv.lan/oauth2/callback
    responseTypes:
      - OIDC_RESPONSE_TYPE_CODE
    skipNativeAppSuccessPage: false
    version: OIDC_VERSION_1_0
  writeConnectionSecretToRef:
    name: bazarr-oidc
    namespace: bazarr
