apiVersion: application.zitadel.didactiklabs.io/v1alpha1
kind: Oidc
metadata:
  name: jellyfin
spec:
  forProvider:
    accessTokenRoleAssertion: false
    accessTokenType: OIDC_TOKEN_TYPE_BEARER
    additionalOrigins: []
    appType: OIDC_APP_TYPE_WEB
    authMethodType: OIDC_AUTH_METHOD_TYPE_BASIC
    clockSkew: 0s
    devMode: false
    grantTypes:
      - OIDC_GRANT_TYPE_AUTHORIZATION_CODE
    idTokenRoleAssertion: false
    idTokenUserinfoAssertion: false
    name: jellyfin
    orgIdRef:
      name: bealv
    postLogoutRedirectUris:
      - '*'
    projectIdRef:
      name: public
    redirectUris:
      - https://jellyfin.bealv.io/sso/OID/redirect/zitadel
      - https://jellyfin.bealv.io/sso/OID/r/zitadel
    responseTypes:
      - OIDC_RESPONSE_TYPE_CODE
    skipNativeAppSuccessPage: false
    version: OIDC_VERSION_1_0
  writeConnectionSecretToRef:
    name: jellyfin-oidc
    namespace: jellyfin
