apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
spec:
  accessModes: ['ReadWriteOnce']
  resources:
    requests:
      storage: 250Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mangas
  annotations:
    nfs.io/storage-path: '/prod-k8s/media/mangas'
spec:
  accessModes: ['ReadWriteOnce']
  storageClassName: 'hdda'
  resources:
    requests:
      storage: 1000Gi
