apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: komf-secrets
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: komf-secrets
  data:
    - secretKey: KOMF_KOMGA_USER
      remoteRef:
        key: secrets-bealv/komga/config
        property: email_admin
    - secretKey: KOMF_KOMGA_PASSWORD
      remoteRef:
        key: secrets-bealv/komga/config
        property: password
    - secretKey: KOMGA_DISCORD_WEBHOOKS
      remoteRef:
        key: secrets-bealv/komf/config
        property: KOMF_DISCORD_WEBHOOKS
