apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-secrets
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: homepage-secrets
  data:
    - secretKey: immichapikey
      remoteRef:
        key: secrets-bealv/immich/config
        property: apikey
    - secretKey: jellyfinapikey
      remoteRef:
        key: secrets-bealv/jellyfin/config
        property: apikey
    - secretKey: komgaapikey
      remoteRef:
        key: secrets-bealv/komga/config
        property: apikey_homepage
    - secretKey: komgausername
      remoteRef:
        key: secrets-bealv/komga/config
        property: email_homepage
    - secretKey: komgapassword
      remoteRef:
        key: secrets-bealv/komga/config
        property: password_homepage
