apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-secrets
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: homepage-secrets
  data:
    - secretKey: immichapikey
      remoteRef:
        key: secrets-bealv/immich/config
        property: apikey
    - secretKey: jellyfinapikey
      remoteRef:
        key: secrets-bealv/jellyfin/config
        property: apikey
    - secretKey: komgaapikey
      remoteRef:
        key: secrets-bealv/komga/config
        property: apikey_homepage
    - secretKey: komgausername
      remoteRef:
        key: secrets-bealv/komga/config
        property: email_homepage
    - secretKey: komgapassword
      remoteRef:
        key: secrets-bealv/komga/config
        property: password_homepage
    - secretKey: sonarrapikey
      remoteRef:
        key: secrets-bealv/sonarr/config
        property: API_KEY
    - secretKey: radarrapikey
      remoteRef:
        key: secrets-bealv/radarr/config
        property: API_KEY
    - secretKey: prowlarrapikey
      remoteRef:
        key: secrets-bealv/prowlarr/config
        property: API_KEY
    - secretKey: bazarrapikey
      remoteRef:
        key: secrets-bealv/bazarr/config
        property: API_KEY
    - secretKey: grafanausername
      remoteRef:
        key: secrets-bealv/grafana/config
        property: username
    - secretKey: grafanapassword
      remoteRef:
        key: secrets-bealv/grafana/config
        property: password
