apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: plex-wireguard
  data:
    - secretKey: wg0.conf
      remoteRef:
        key: secrets-bealv/plex/wireguard
        property: wg0.conf