apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: jellyfin-data
  namespace: velero
spec:
  schedule: 0 12 * * *
  template:
    includedNamespaces:
      - jellyfin
    includedResources:
      - pvc
    labelSelector:
      matchLabels:
        backup: 'true'
    snapshotMoveData: false
    ttl: 160h00s
    resourcePolicy:
      apiGroup: v1
      kind: ConfigMap
      name: velero-volume-policies
