apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: jellyfin-data
  namespace: velero
spec:
  schedule: 0 12 * * *
  template:
    defaultVolumesToFsBackup: true
    includedNamespaces:
      - jellyfin
    includedResources:
      - pvc
    labelSelector:
      matchLabels:
        backup: 'true'
    snapshotMoveData: true
    ttl: 160h0m0s
