apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: prowlarr-data
  namespace: velero
spec:
  schedule: 0 12 * * *
  template:
    defaultVolumesToFsBackup: true
    includedNamespaces:
      - prowlarr
    includedResources:
      - pvc
      - pods
    labelSelector:
      matchLabels:
        backup: 'true'
    snapshotMoveData: false
    ttl: 160h00s
    resourcePolicy:
      apiGroup: v1
      kind: ConfigMap
      name: velero-volume-policies
