apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: zitadel-data
  namespace: velero
spec:
  schedule: 0 12 * * *
  template:
    includedNamespaces:
      - zitadel
    includedResources:
      - pvc
    snapshotMoveData: false
    ttl: 160h00s
    resourcePolicy:
      apiGroup: v1
      kind: ConfigMap
      name: velero-volume-policies
