apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: memos-postgres
spec:
  instances: 1
  storage:
    storageClass: disk-hddb
    size: 50Gi
  bootstrap:
    initdb:
      database: memos
      owner: memos
      secret:
        name: memos-secrets
