apiVersion: v1
kind: ConfigMap
metadata:
  name: contour
  namespace: projectcontour
data:
  contour.yaml: |
    disablePermitInsecure: false
    enableExternalNameService: false
    accesslog-format: envoy
    # cluster:
    #   per-connection-buffer-limit-bytes: 4073741824
    # listener:
    #   per-connection-buffer-limit-bytes: 4073741824
