apiVersion: v1
kind: ConfigMap
metadata:
  name: contour
  namespace: projectcontour
data:
  contour.yaml: |
    disablePermitInsecure: false
    enableExternalNameService: false
    accesslog-format: envoy
    cluster:
      per-connection-buffer-limit-bytes: 1073741824
