namespace: ingress-contour-external
resources:
  - upstream/
  - gateway.yaml
  - gatewayclass.yaml
  # - cloudflared.yaml
patches:
  - path: envoy-patch.yaml
  - path: contour-patch.yaml
  - path: cm-patch.yaml
    target:
      kind: ConfigMap
      name: contour
