apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fmd2
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops/apps/fmd2
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
