apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kgateway
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops/apps/kgateway
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
  dependsOn:
    - name: gateway-api
