apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zot
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops/apps/zot
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
