apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin
spec:
  parentRefs:
    - name: public
      namespace: istio-system
      sectionName: https
  hostnames:
    - jellyfin.bealv.io
  rules:
    - backendRefs:
        - name: jellyfin
          port: 8096
