apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  annotations:
    cert-manager.io/cluster-issuer: bealvio
    projectcontour.io/websocket-routes: /socket
    external-dns.alpha.kubernetes.io/target: bealv.io
  labels:
    probe: enabled
spec:
  ingressClassName: external
  rules:
    - host: 'jellyfin.bealv.io'
      http:
        paths:
          - path: /socket
            pathType: Prefix
            backend:
              service:
                name: jellyfin
                port:
                  number: 8096
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin
                port:
                  number: 8096
  tls:
    - hosts:
        - 'jellyfin.bealv.io'
      secretName: jellyfin-tls
