apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin
resources:
  - deploy.yaml
  - service.yaml
  - ingress.yaml
  - namespace.yaml
  - cm.yaml
  - custom-css-cm.yaml
  - pvc.yaml
