apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prowlarr
resources:
  - deploy.yaml
  - service.yaml
  - ingress.yaml
  - namespace.yaml
  - secrets.yaml
  - pvcs.yaml
  - flaresolverr.yaml
  - oauth2-proxy
