apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-secrets
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: prowlarr-secrets
  data:
    - secretKey: API_KEY
      remoteRef:
        key: secrets-bealv/prowlarr/config
        property: API_KEY
