apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-qvcoaching
  namespace: qvcoaching
spec:
  dnsNames:
    - qvcoaching.fr
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: qvcoaching
  secretName: tls-qvcoaching
  usages:
    - digital signature
    - key encipherment
