apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: qvcoaching
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: qvcoaching-account-key
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
            - name: qvcoaching-listener
              namespace: qvcoaching
              kind: XListenerSet
              group: gateway.networking.x-k8s.io