apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: outline-postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  enableSuperuserAccess: true
  superuserSecret:
    name: outline-secrets
  bootstrap:
    initdb:
      database: outline
      owner: postgres
      secret:
        name: outline-secrets
  storage:
    size: 8Gi
