apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: outline-dragonfly
spec:
  replicas: 3
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
