apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: outline-dragonfly
spec:
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  args:
    - --default_lua_flags=allow-undeclared-keys,disable-atomicity
