apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: outline
resources:
  - namespace.yaml
  - cnpg.yaml
  - dragonfly.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - ingress.yaml
  - external-secret.yaml
