apiVersion: zitadel.didactiklabs.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: zitadel-crossplane
      namespace: crossplane-system
      key: credentials
---
