apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zitadel-crossplane
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: zitadel-crossplane
    template:
      engineVersion: v2
      data:
        credentials: |
          {
            "domain": "zitadel.bealv.io",
            "insecure": "false",
            "jwt_profile_json": "{{ .jsonjwt }}",
            "port": "443"
          }
  data:
    - secretKey: jsonjwt
      remoteRef:
        key: secrets-bealv/zitadel/crossplane
        property: jsonjwt
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zitadel-github
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: zitadel-github
  data:
    - secretKey: secretid
      remoteRef:
        key: secrets-bealv/github/oauth2
        property: secretid
