apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zitadel-crossplane
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: zitadel-crossplane
    template:
      engineVersion: v2
      data:
        credentials: |
          {
            "domain": "zitadel.bealv.io",
            "insecure": "false",
            "jwt_profile_json": "{{ .jsonjwt }}"
            "port": "443"
          }
  data:
    - secretKey: jsonjwt
      remoteRef:
        key: secrets/zitadel/crossplane
        property: jsonjwt
