apiVersion: v1
kind: ServiceAccount
metadata:
  name: zot-secret-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zot-secret-reader-role
rules:
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['get', 'list', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zot-secret-reader-rolebinding
subjects:
  - kind: ServiceAccount
    name: zot-secret-reader
roleRef:
  kind: Role
  name: zot-secret-reader-role
  apiGroup: rbac.authorization.k8s.io
