apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: zot-store
spec:
  provider:
    kubernetes:
      remoteNamespace: zot
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: 'zot-secret-reader'
