apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zot-secrets
spec:
  refreshInterval: '1h'
  secretStoreRef:
    kind: SecretStore
    name: zot-store
  target:
    name: zot-secrets
    template:
      engineVersion: v2
      data:
        config.json: |-
          {
            "storage": {
              "rootDirectory": "/var/lib/registry",
              "commit": true,
              "dedupe": true,
              "gc": true
            },
            "http": {
              "address": "0.0.0.0",
              "port": "5000",
              "externalUrl": "https://zot.bealv.io",
              "auth": {
                "openid": {
                  "providers": {
                    "oidc": {
                      "name": "Zitadel SSO",
                      "issuer": "https://zitadel.bealv.io",
                      "clientid": "{{ .client_id }}",
                      "clientsecret": "{{ .client_secret }}",
                      "scopes": ["openid","user","email","groups"]
                    }
                  }
                }
              },
              "accessControl": {
                "adminPolicy": {
                  "groups": ["public-admin","bealv-admin"],
                  "actions": ["read", "create", "update", "delete"]
                },
                "repositories": {
                  "public/**": {
                    "anonymousPolicy": [
                      "read"
                    ]
                  }
                }
              }
            },
            "log": { "level": "debug" },
            "extensions": {
              "search": {
                "enable": true,
                "cve": {
                  "updateInterval": "2h"
                }
              },
              "ui": {
                "enable": true
              }
            }
          }
  data:
    - secretKey: client_id
      remoteRef:
        key: zot-oidc
        property: attribute.client_id
    - secretKey: client_secret
      remoteRef:
        key: zot-oidc
        property: attribute.client_secret
