apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-hdda
  namespace: nfs-hdda
spec:
  interval: 30m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: '4.0.18'
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: nfs-hdda
      interval: 12h
  values:
    nfs:
      mountOptions:
        - hard
        - noatime
        - timeo=600
        - retry=5
        - actimeo=3
        - nodiratime
        - intr
      path: /bealv/hdda
      reclaimPolicy: Retain
      server: 10.250.0.2
      volumeName: nfs-subdir-external-provisioner-root
    rbac:
      create: true
    replicaCount: 1
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
    storageClass:
      accessModes: ReadWriteOnce
      allowVolumeExpansion: true
      archiveOnDelete: true
      create: true
      defaultClass: false
      name: hdda
      onDelete: null
      pathPattern: ${.PVC.annotations.nfs.io/storage-path}
      reclaimPolicy: Delete
