apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: contour-external
spec:
  namespaceSelector:
    matchNames:
      - ingress-contour-external
  selector:
    matchLabels:
      app: contour
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: contour
  name: contour-service
  namespace: ingress-contour-external
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: metrics
      port: 8000
      targetPort: metrics
  selector:
    app: contour
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-external
spec:
  namespaceSelector:
    matchNames:
      - ingress-contour-external
  selector:
    matchLabels:
      app: envoy
  endpoints:
    - port: metrics
      interval: 30s
      path: /stats/prometheus
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: envoy
  name: envoy-service
  namespace: ingress-contour-external
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: metrics
      port: 8002
      targetPort: metrics
  selector:
    app: envoy
