apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-general
  labels:
    dashboards: 'grafana'
    app: grafana-general
    alertmanager-default: 'true'
spec:
  version: 12.1.0
  config:
    server:
      root_url: https://grafana.bealv.lan
    log:
      mode: 'console'
    auth:
      disable_login_form: 'true'
    security:
      admin_user: root
      admin_password: root
    auth.generic_oauth:
      enabled: 'true'
      name: 'Zitadel SSO'
      allow_sign_up: 'true'
      client_id: ${AUTH_CLIENT_ID}
      client_secret: ${AUTH_CLIENT_SECRET}
      scopes: 'openid email profile offline_access roles'
      email_attribute_path: email
      login_attribute_path: username
      name_attribute_path: full_name
      groups_attribute_path: groups
      auth_url: 'https://zitadel.bealv.io/oauth/v2/authorize'
      token_url: 'https://zitadel.bealv.io/oauth/v2/token'
      api_url: 'https://zitadel.bealv.io/oidc/v1/userinfo'
      role_attribute_path: "contains(groups[*], 'bealv-admin') && 'Admin' || 'Viewer'"
      role_attribute_strict: 'true'
      allow_assign_grafana_admin: 'true'
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: AUTH_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: grafana-oidc
                      key: attribute.client_id
                - name: AUTH_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: grafana-oidc
                      key: attribute.client_secret
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: grafana-secrets
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: grafana-secrets
