resources:
  - servicemonitors/
  - grafana.yaml
  - grafana-ing.yaml
  - alertmanager-config.yaml
  - additional-datasources.yaml
  - secrets.yaml
  - grafana-prom-netpol.yaml
  - grafana-netpol.yaml
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: notImportantHere
      namespace: monitoring
    unsetOnly: true
    setRoleBindingSubjects: none
