apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
spec:
  replicas: 1
  retentionSize: 10GiB
  resources:
    requests:
      cpu: 1
      memory: 700Mi
    limits:
      cpu: 1
      memory: 700Mi
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: 'disk-hdd'
        resources:
          requests:
            storage: 20Gi
