apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-secrets
  data:
    - secretKey: discordwebhookurl
      remoteRef:
        key: secrets-bealv/grafana/config
        property: discordwebhookurl
    - secretKey: username
      remoteRef:
        key: secrets-bealv/grafana/config
        property: username
    - secretKey: password
      remoteRef:
        key: secrets-bealv/grafana/config
        property: password
