apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: 0.10.3
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: immich
      interval: 12h
  values:
    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            env:
              DB_VECTOR_EXTENSION: vectorchord
              REDIS_HOSTNAME: 'immich-dragonfly'
              DB_HOSTNAME: 'immich-postgres-rw'
              DB_USERNAME: 'immich'
              DB_DATABASE_NAME: 'immich'
              IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    key: password
                    name: immich-secrets
            image:
              tag: v2.3.1
    immich:
      metrics:
        enable: false
      probes:
        liveness:
          spec:
            initialDelaySeconds: 3600
        readiness:
          spec:
            initialDelaySeconds: 3600
        startup:
          spec:
            failureThreshold: 1000
            periodSeconds: 10
      persistence:
        library:
          existingClaim: immich-data
    # Immich components
    server:
      enabled: true
      controllers:
        strategy: Recreate
        main:
          containers:
            main:
              resources:
                requests:
                  cpu: 200m
                  memory: 2Gi
                limits:
                  gpu.intel.com/i915: 1
                  cpu: 2
                  memory: 4Gi
              serviceAccount:
                create: true
                name: 'immich'
      automountServiceAccountToken: true
      ingress:
        main:
          enabled: false
    machine-learning:
      enabled: true
      persistence:
        cache:
          enabled: true
          size: 10Gi
          # Optional: Set this to pvc to avoid downloading the ML models every start.
          type: emptyDir
          accessMode: ReadWriteOnce
          storageClass: disk
      controllers:
        main:
          containers:
            main:
              resources:
                requests:
                  cpu: 200m
                  memory: 2Gi
                limits:
                  cpu: 6
                  memory: 2Gi
              env:
                TRANSFORMERS_CACHE: /cache
