apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich
  annotations:
    cert-manager.io/cluster-issuer: bealvio
    projectcontour.io/websocket-routes: /api/socket.io
    external-dns.alpha.kubernetes.io/target: bealv.io
  labels:
    probe: enabled
spec:
  ingressClassName: external
  rules:
    - host: 'immich.bealv.io'
      http:
        paths:
          - path: /api/socket.io
            pathType: Prefix
            backend:
              service:
                name: immich-server-custom
                port:
                  number: 2283
          - path: /
            pathType: Prefix
            backend:
              service:
                name: immich-server
                port:
                  number: 2283
  tls:
    - hosts:
        - 'immich.bealv.io'
      secretName: immich-tls
