apiVersion: hyperspike.io/v1
kind: Valkey
metadata:
  labels:
  name: immich-valkey
spec:
  # the number of master nodes in the cluster
  nodes: 1
  # the number of replicas per master node
  replicas: 0
  # the resource requests and limits for the Valkey Container
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  # boolean value to enable or disable TLS, cert-manager is required for TLS
  tls: false
  # the cert issuer to use for the Valkey Container
  certIssuer: bealv
  # the cert issuer type to use for the Valkey Container (ClusterIssuer or Issuer)
  certIssuerType: ClusterIssuer
  # Enalbe or disable external access to the Valkey Container
  # Volume Permissions ensures that the PVC volume ownership is set to the correct user
  volumePermissions: true
  # the image to use for the Valkey Sidecar Container/Exporter image
  exporterImage: ghcr.io/hyperspike/valkey-sidecar:latest
  # the image to use for the Valkey Container
  image: ghcr.io/hyperspike/valkey:8.1.3
  anonymousAuth: true
  storage:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
      storageClassName: disk
