apiVersion: apps/v1
kind: Deployment
metadata:
  name: solidtime
  labels: &default
    app: solidtime
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: *default
  template:
    metadata:
      labels: *default
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
        - name: app
          image: solidtime/solidtime:latest
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - configMapRef:
                name: solidtime-config
            - secretRef:
                name: solidtime-secrets
          env:
            - name: CONTAINER_MODE
              value: "http"
            - name: AUTO_DB_MIGRATE
              value: "true"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: solidtime-secrets
                  key: password
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: solidtime-secrets
                  key: username
            - name: DB_HOST
              value: solidtime-postgres-rw
            - name: DB_DATABASE
              value: solidtime
          volumeMounts:
            - name: app-storage
              mountPath: /var/www/html/storage
        - name: scheduler
          image: solidtime/solidtime:latest
          envFrom:
            - configMapRef:
                name: solidtime-config
            - secretRef:
                name: solidtime-secrets
          env:
            - name: CONTAINER_MODE
              value: "scheduler"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: solidtime-secrets
                  key: password
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: solidtime-secrets
                  key: username
            - name: DB_HOST
              value: solidtime-postgres-rw
            - name: DB_DATABASE
              value: solidtime
          volumeMounts:
            - name: app-storage
              mountPath: /var/www/html/storage
        - name: queue
          image: solidtime/solidtime:latest
          envFrom:
            - configMapRef:
                name: solidtime-config
            - secretRef:
                name: solidtime-secrets
          env:
            - name: CONTAINER_MODE
              value: "worker"
            - name: WORKER_COMMAND
              value: "php /var/www/html/artisan queue:work"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: solidtime-secrets
                  key: password
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: solidtime-secrets
                  key: username
            - name: DB_HOST
              value: solidtime-postgres-rw
            - name: DB_DATABASE
              value: solidtime
          volumeMounts:
            - name: app-storage
              mountPath: /var/www/html/storage
        - name: gotenberg
          image: gotenberg/gotenberg:8
          ports:
            - name: gotenberg
              containerPort: 3000
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: solidtime-app-storage