apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: solidtime-secrets
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: solidtime-secrets
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: secrets-bealv/solidtime/config
        property: APP_KEY
    - secretKey: PASSPORT_PRIVATE_KEY
      remoteRef:
        key: secrets-bealv/solidtime/config
        property: PASSPORT_PRIVATE_KEY
    - secretKey: PASSPORT_PUBLIC_KEY
      remoteRef:
        key: secrets-bealv/solidtime/config
        property: PASSPORT_PUBLIC_KEY
    - secretKey: MAIL_USERNAME
      remoteRef:
        key: secrets-bealv/gmail/bealv
        property: username
    - secretKey: MAIL_PASSWORD
      remoteRef:
        key: secrets-bealv/gmail/bealv
        property: password
    - secretKey: MAIL_HOST
      remoteRef:
        key: secrets-bealv/gmail/bealv
        property: host
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: solidtime-postgres-superuser
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: solidtime-postgres-superuser
  data:
    - secretKey: username
      remoteRef:
        key: secrets-bealv/solidtime/postgres-superuser
        property: username
    - secretKey: password
      remoteRef:
        key: secrets-bealv/solidtime/postgres-superuser
        property: password