apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: solidtime
resources:
  - namespace.yaml
  - external-secret.yaml
  - cnpg.yaml
  - pvcs.yaml
  - configmap.yaml
  - app-deploy.yaml
  - scheduler-deploy.yaml
  - queue-deploy.yaml
  - gotenberg-deploy.yaml
  - app-service.yaml
  - gotenberg-service.yaml
  - httproute.yaml