apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: flux-system
spec:
  interval: 1h0m0s
  targetNamespace: istio-system
  dependsOn:
    - name: istio-base
  chart:
    spec:
      chart: cni
      version: '1.23.2'
      sourceRef:
        kind: HelmRepository
        name: istio
  values:
    profile: ambient
---
