apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-istiod
  namespace: flux-system
spec:
  interval: 1h0m0s
  targetNamespace: istio-system
  dependsOn:
    - name: istio-base
  chart:
    spec:
      chart: istiod
      version: '1.23.2'
      sourceRef:
        kind: HelmRepository
        name: istio3
  values:
    profile: ambient
    pilot:
      env:
        PILOT_ENABLE_ALPHA_GATEWAY_API: true
---
