apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ombi
resources:
  - service.yaml
  - httproute.yaml
  - namespace.yaml
  - deploy.yaml
  - secrets.yaml
  - cnpg.yaml
  - oauth2-proxy
