apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ombi-secrets
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ombi-secrets
  data:
    - secretKey: username
      remoteRef:
        key: secrets-bealv/ombi/postgres
        property: username
    - secretKey: password
      remoteRef:
        key: secrets-bealv/ombi/postgres
        property: password
    - secretKey: database
      remoteRef:
        key: secrets-bealv/ombi/postgres
        property: database
