apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-secrets
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: radarr-secrets
  data:
    - secretKey: API_KEY
      remoteRef:
        key: secrets-bealv/radarr/config
        property: API_KEY
