apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-zitadel
spec:
  package: banhcanh/provider-zitadel:v0.4.1
---
apiVersion: zitadel.didactiklabs.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: zitadel-crossplane
      namespace: crossplane-system
      key: credentials
---
