apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  labels:
    backup: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
