apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden-secrets
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vaultwarden-secrets
  data:
    - secretKey: admin_token
      remoteRef:
        key: secrets-bealv/vaultwarden/config
        property: admin_token
