apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-secrets
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vaultwarden-secrets
  data:
    - secretKey: admin_token
      remoteRef:
        key: secrets-bealv/vaultwarden/config
        property: admin_token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smtp-secrets
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: smtp-secrets
  data:
    - secretKey: from
      remoteRef:
        key: secrets-bealv/gmail/bealv
        property: from
    - secretKey: host
      remoteRef:
        key: secrets-bealv/gmail/bealv
        property: host
    - secretKey: password
      remoteRef:
        key: secrets-bealv/vaultwarden/config
        property: smtppassword
    - secretKey: port
      remoteRef:
        key: secrets-bealv/gmail/bealv
        property: port
    - secretKey: username
      remoteRef:
        key: secrets-bealv/gmail/bealv
        property: username
