kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: https
  namespace: kgateway-system
  annotations:
    cert-manager.io/cluster-issuer: bealvio
    external-dns.alpha.kubernetes.io/target: bealv.io
spec:
  gatewayClassName: kgateway
  infrastructure:
    parametersRef:
      group: gateway.kgateway.dev
      kind: GatewayParameters
      name: gwp-static-ip
  listeners:
    - protocol: HTTP
      port: 80
      name: http
      hostname: '*.bealv.io'
      allowedRoutes:
        namespaces:
          from: All
    - protocol: HTTPS
      port: 443
      name: https
      hostname: '*.bealv.io'
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: bealvio-wildcard-tls
    - protocol: HTTPS
      port: 443
      name: https-qvcoaching
      hostname: 'qvcoaching.fr'
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: tls-qvcoaching
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: gwp-static-ip
  namespace: kgateway-system
spec:
  kube:
    service:
      type: LoadBalancer
      extraAnnotations:
        lbipam.cilium.io/ips: '10.250.128.5'
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-redirect
  annotations:
    external-dns.alpha.kubernetes.io/controller: ignore
spec:
  parentRefs:
    - name: https
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
