apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kgateway
  namespace: kgateway-system
spec:
  type: 'oci'
  interval: 5m0s
  url: oci://cr.kgateway.dev/kgateway-dev/charts
