apiVersion: gateway.kgateway.dev/v1alpha1
kind: HTTPListenerPolicy
metadata:
  name: upgrades
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: https
  upgradeConfig:
    enabledUpgrades:
      - 'websocket'
