apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dollardollar-secrets
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: dollardollar-secrets
    template:
      engineVersion: v2
      data:
        SQLALCHEMY_DATABASE_URI: 'postgresql://{{ .username }}:{{ .password }}@dollardollar-postgres-rw:5432/dollardollar'
        secretkey: '{{ .secretkey }}'
        username: '{{ .username }}'
        password: '{{ .password }}'
  data:
    - secretKey: secretkey
      remoteRef:
        key: secrets-bealv/dollardollar/config
        property: secretkey
    - secretKey: username
      remoteRef:
        key: secrets-bealv/dollardollar/postgres
        property: username
    - secretKey: password
      remoteRef:
        key: secrets-bealv/dollardollar/postgres
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smtp-secrets
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: smtp-secrets
  data:
    - secretKey: from
      remoteRef:
        key: secrets-bealv/gmail/bealv
        property: from
    - secretKey: host
      remoteRef:
        key: secrets-bealv/gmail/bealv
        property: host
    - secretKey: password
      remoteRef:
        key: secrets-bealv/gmail/bealv
        property: password
    - secretKey: port
      remoteRef:
        key: secrets-bealv/gmail/bealv
        property: port
    - secretKey: username
      remoteRef:
        key: secrets-bealv/gmail/bealv
        property: username
