apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      securityContext:
        sysctls:
          - name: 'net.ipv4.conf.all.src_valid_mark'
            value: '1'
      containers:
        - name: qbittorrent
          command:
            - /bin/bash
            - -c
            - cp /config/wireguard/wg0.conf.tmpl /config/wireguard/wg0.conf && /usr/local/bin/init.sh
          securityContext:
            privileged: true
          image: binhex/arch-qbittorrentvpn
          ports:
            - containerPort: 8080
              name: qbittorrent
          volumeMounts:
            - name: downloads
              mountPath: /downloads
            - name: config
              mountPath: /config
            - name: qbittorrent-secrets
              mountPath: '/config/wireguard/wg0.conf.tmpl'
              subPath: 'wg0.conf'
          env:
            - name: VPN_ENABLED
              value: 'yes'
            - name: VPN_PROV
              value: 'custom'
            - name: VPN_CLIENT
              value: 'wireguard'
            - name: ENABLE_STARTUP_SCRIPTS
              value: 'no'
            - name: STRICT_PORT_FORWARD
              value: 'no'
            - name: LAN_NETWORK
              value: '10.0.0.0/8,172.16.0.0/16,172.17.0.0/16'
            - name: NAME_SERVERS
              value: '10.250.0.11'
            - name: DEBUG
              value: 'false'
            - name: WEBUI_PORT
              value: '8080'
            - name: UMASK
              value: '000'
            - name: PUID
              value: '0'
            - name: PGID
              value: '0'
      volumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: qbittorrent-secrets
          secret:
            secretName: qbittorrent-secrets
