apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  annotations:
    nfs.io/storage-path: '/prod-k8s/media/downloads'
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hdda
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  labels:
    backup: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: saved-movies
  annotations:
    nfs.io/storage-path: "/saved_movies"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "hddb"
  resources:
    requests:
      storage: 1Gi