apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set
spec:
  interval: 5m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.11.0
      sourceRef:
        kind: HelmRepository
        name: arc
      interval: 12h
  values:
    runnerScaleSetName: 'bealv-runners'
    githubConfigUrl: 'https://github.com/Bealvio'
    githubConfigSecret: 'github-action-chan'
    minRunners: 0
    maxRunners: 2
    template:
      spec:
        containers:
          - name: runner
            image: zot.bealv.io/public/action-runner-nix:qcv74qplmw10qd4jljj9w2zzn5yvijzz
            resources:
              limits:
                cpu: '500m'
                memory: '1Gi'
              requests:
                cpu: '100m'
                memory: '1Gi'
            env:
              - name: APP_ID
                valueFrom:
                  secretKeyRef:
                    name: github-update-chan
                    key: github_app_id
              - name: APP_PRIVATE_KEY
                valueFrom:
                  secretKeyRef:
                    name: github-update-chan
                    key: github_app_private_key
