apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set
spec:
  interval: 5m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: arc
      interval: 12h
  values:
    runnerScaleSetName: 'bealv-runners'
    githubConfigUrl: 'https://github.com/Bealvio'
    githubConfigSecret: 'github-action-chan'
    minRunners: 0
    maxRunners: 2
    template:
      spec:
        securityContext:
          fsGroup: 1001
        containers:
          - name: runner
            image: zot.bealv.io/public/action-runner-nix:6bpakg1p06srbkcnnv66g5y42hzjcbq6
            resources:
              limits:
                cpu: '3'
                memory: '2Gi'
              requests:
                cpu: '500m'
                memory: '1Gi'
            env:
              - name: NIX_PATH # default nixpkgs
                value: 'nixpkgs=https://releases.nixos.org/nixos/24.11/nixos-24.11.715401.20755fa05115/nixexprs.tar.xz'
              - name: APP_ID
                valueFrom:
                  secretKeyRef:
                    name: github-update-chan
                    key: github_app_id
              - name: APP_PRIVATE_KEY
                valueFrom:
                  secretKeyRef:
                    name: github-update-chan
                    key: github_app_private_key
              - name: REGISTRY_USER
                valueFrom:
                  secretKeyRef:
                    name: github-update-chan
                    key: registry_user
              - name: REGISTRY_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: github-update-chan
                    key: registry_password
            volumeMounts:
              - mountPath: '/home/runner/.github-runner/_work/_temp/_github_home'
                name: home
              - mountPath: '/home/runner/.github-runner/_work/_temp/_github_workflow'
                name: workflows
              - mountPath: '/home/runner/.github-runner/_work/_temp/_runner_file_commands'
                name: commands
              - mountPath: '/home/runner/.github-runner/_work/bealv/bealv'
                name: bealv
              - mountPath: '/home/runner/.github-runner/_work/flux-mgmt/flux-mgmt'
                name: flux-mgmt
        volumes:
          - name: home
            ephemeral:
              volumeClaimTemplate:
                spec:
                  accessModes: ['ReadWriteOnce']
                  storageClassName: 'disk-hddb'
                  resources:
                    requests:
                      storage: 50Gi
          - name: workflows
            ephemeral:
              volumeClaimTemplate:
                spec:
                  accessModes: ['ReadWriteOnce']
                  storageClassName: 'disk-hddb'
                  resources:
                    requests:
                      storage: 50Gi
          - name: commands
            ephemeral:
              volumeClaimTemplate:
                spec:
                  accessModes: ['ReadWriteOnce']
                  storageClassName: 'disk-hddb'
                  resources:
                    requests:
                      storage: 50Gi
          - name: bealv
            ephemeral:
              volumeClaimTemplate:
                spec:
                  accessModes: ['ReadWriteOnce']
                  storageClassName: 'disk-hddb'
                  resources:
                    requests:
                      storage: 50Gi
          - name: flux-mgmt
            ephemeral:
              volumeClaimTemplate:
                spec:
                  accessModes: ['ReadWriteOnce']
                  storageClassName: 'disk-hddb'
                  resources:
                    requests:
                      storage: 50Gi
