apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set
spec:
  interval: 5m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.11.0
      sourceRef:
        kind: HelmRepository
        name: arc
      interval: 12h
  values:
    runnerScaleSetName: 'bealv-runners'
    githubConfigUrl: 'https://github.com/Bealvio'
    githubConfigSecret: 'github-action-chan'
    minRunners: 0
    maxRunners: 2
    template:
      spec:
        containers:
          - name: runner
            image: zot.bealv.io/public/action-runner-nix:lnijpvr0i26qf9f15k1fb7vg2sa78h09
            resources:
              limits:
                cpu: '500m'
                memory: '1Gi'
              requests:
                cpu: '100m'
                memory: '1Gi'
            env:
              - name: NIX_PATH # default nixpkgs
                value: 'nixpkgs=https://releases.nixos.org/nixos/24.11/nixos-24.11.715401.20755fa05115/nixexprs.tar.xz'
              - name: APP_ID
                valueFrom:
                  secretKeyRef:
                    name: github-update-chan
                    key: github_app_id
              - name: APP_PRIVATE_KEY
                valueFrom:
                  secretKeyRef:
                    name: github-update-chan
                    key: github_app_private_key
              - name: REGISTRY_USER
                valueFrom:
                  secretKeyRef:
                    name: github-update-chan
                    key: registry_user
              - name: REGISTRY_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: github-update-chan
                    key: registry_password
