apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arc
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github-action-chan
  data:
    - secretKey: github_app_id
      remoteRef:
        key: secrets-bealv/github/arc
        property: appid
    - secretKey: github_app_installation_id
      remoteRef:
        key: secrets-bealv/github/arc
        property: installid
    - secretKey: github_app_private_key
      remoteRef:
        key: secrets-bealv/github/arc
        property: privatekey
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arc-updatecli
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github-update-chan
  data:
    - secretKey: github_app_id
      remoteRef:
        key: secrets-bealv/github/updatecli
        property: appid
    - secretKey: github_app_installation_id
      remoteRef:
        key: secrets-bealv/github/updatecli
        property: installid
    - secretKey: github_app_private_key
      remoteRef:
        key: secrets-bealv/github/updatecli
        property: privatekey
    - secretKey: registry_user
      remoteRef:
        key: secrets-bealv/zot/localusers
        property: ci_user
    - secretKey: registry_password
      remoteRef:
        key: secrets-bealv/zot/localusers
        property: ci_password
