apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secrets
spec:
  refreshInterval: '1h'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy-secrets
  data:
    - secretKey: cookie-secret
      remoteRef:
        key: secrets-bealv/oauth2-proxy/config
        property: cookie-secret
