apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: zitadel-postgres
spec:
  instances: 1
  enableSuperuserAccess: true
  superuserSecret:
    name: zitadel-secrets
  storage:
    size: 30Gi
  bootstrap:
    initdb:
      database: zitadel
      owner: zitadel
      secret:
        name: zitadel-secrets
